from __future__ import annotations

# Rolling scene summary: compress last 1-2 scene captions into 1-2 sentences
# Used to feed prev_scene_summary into each Qwen frame prompt

SCENE_SUMMARY_SYSTEM = """You are a concise story summarizer. Given scene analysis data, write 1-2 sentences summarizing what happened. Focus on: who did what, what conflict/tension exists, what is likely to happen next. Be specific, no filler."""


def build_scene_summary_prompt(frame_analyses: list[dict]) -> str:
    """Build prompt to compress recent frame analyses into rolling summary.

    Extracts key fields (caption, story_beat.beat_type, causality.likely_consequence,
    people[].pid) from the last 3 frame analyses and formats them as a compact context
    string.

    This is NOT a model call — it just builds the input text. The actual summary is
    generated by Qwen itself in the context_builder.

    Args:
        frame_analyses: List of QwenFrameOutput dicts (last 3-5 frames of previous scene).

    Returns:
        A compact context string describing the recent frames, suitable for injecting
        into prev_scene_summary in the next frame prompt.
    """
    # Take at most the last 3 frames to keep the summary tight
    recent = frame_analyses[-3:] if len(frame_analyses) > 3 else frame_analyses

    if not recent:
        return "No previous scene analysis available."

    parts: list[str] = []

    for i, analysis in enumerate(recent):
        frame_parts: list[str] = []

        # Caption
        caption = analysis.get("caption", "")
        if caption:
            frame_parts.append(f"Caption: {caption}")

        # Beat type from story_beat
        story_beat = analysis.get("story_beat") or {}
        beat_type = story_beat.get("beat_type", "")
        act_position = story_beat.get("act_position", "")
        if beat_type:
            beat_str = beat_type
            if act_position:
                beat_str = f"{beat_type} ({act_position})"
            frame_parts.append(f"Beat: {beat_str}")

        # Likely consequence from causality
        causality = analysis.get("causality") or {}
        likely_consequence = causality.get("likely_consequence", "")
        if likely_consequence:
            frame_parts.append(f"Consequence implied: {likely_consequence}")

        # People present
        people = analysis.get("people") or []
        pids = [p.get("pid", "") for p in people if p.get("pid")]
        if pids:
            frame_parts.append(f"People: {', '.join(pids)}")

        # Timestamp
        timestamp = analysis.get("t")
        if timestamp is not None:
            frame_parts.append(f"t={timestamp:.1f}s")

        if frame_parts:
            frame_label = f"[Frame {i + 1}]"
            parts.append(f"{frame_label} " + " | ".join(frame_parts))

    return "\n".join(parts)
